#version: '3.9'
#
#services:
#  bot:
#    build:
#      dockerfile: ./Dockerfile
#    command: "python3 bot.py"
##    restart: always
#    volumes:
#      - ./:/app

version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "python3 bot.py"
    restart: always
    volumes:
      - ./:/app
    environment:
      - DB_NAME=bot_database
      - DB_USER=bot_user
      - DB_PASSWORD=securepassword
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    networks:
      - bot_network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: bot_database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot_network

volumes:
  postgres_data:

networks:
  bot_network:
